version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-mutantes
    environment:
      POSTGRES_USER: mutant_user
      POSTGRES_PASSWORD: mutant_pass
      POSTGRES_DB: mutantdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mutantes-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mutantdb
      SPRING_DATASOURCE_USERNAME: mutant_user
      SPRING_DATASOURCE_PASSWORD: mutant_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data:
